services:
  fastapi:
    image: fastapilogfire
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./server/app:/code/app
    command: fastapi run app/main.py --host 0.0.0.0 --port 80 --reload
    env_file:
      - server/app/.env

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  otel-tui:
    image: ymtdzzz/otel-tui:latest
    container_name: otel-tui
    ports:
      - "4318:4318"
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - fastapi
    command: [ "/otel-tui" ]

volumes:
  qdrant_data: