services:
  api:
    image: fastapilogfire
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    networks:
      - internal

networks:
  internal: {}