services:
  fastapi:
    image: fastapilogfire
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./api/app:/code/app
    command: fastapi run app/main.py --host 0.0.0.0 --port 80 --reload
    networks:
      - internal
    env_file:
      - api/app/.env

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  otel-tui:
    image: ymtdzzz/otel-tui:latest
    container_name: otel-tui
    ports:
      - "4318:4318"  # OTLP receiver
    tty: true
    stdin_open: true  # Optional: allows interactive input if needed
    restart: unless-stopped
    depends_on:
      - fastapi
    # Optional: auto-run otel-tui with custom UI or refresh rate
    command: [ "/otel-tui" ]

networks:
  internal: {}
volumes:
  qdrant_data: