services:
  fastapi:
    image: fastapilogfire
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./server/app:/code/app
    command: fastapi run app/main.py --host 0.0.0.0 --port 80 --reload
    env_file:
      - server/.env

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  otel:
    image: jaegertracing/jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug

# DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=llm_eval
    ports:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data


volumes:
  qdrant_data:
  database_data:
    driver: local